// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project1.Models;

namespace project1.Migrations
{
    [DbContext(typeof(TaskListContext))]
    partial class TaskListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("project1.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CategoryId = 2,
                            Completed = false,
                            DueDate = "2-15-2022",
                            Quadrant = 1,
                            Task = "Get Caden a girlfriend"
                        },
                        new
                        {
                            TaskId = 2,
                            CategoryId = 3,
                            Completed = true,
                            DueDate = "12-31-2022",
                            Quadrant = 2,
                            Task = "Find out how Hayden got so dang cute"
                        },
                        new
                        {
                            TaskId = 3,
                            CategoryId = 1,
                            Completed = false,
                            DueDate = "2-11-2022",
                            Quadrant = 2,
                            Task = "Get as swole as Ben"
                        });
                });

            modelBuilder.Entity("project1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryTitle = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryTitle = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryTitle = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryTitle = "Church"
                        });
                });

            modelBuilder.Entity("project1.Models.ApplicationResponse", b =>
                {
                    b.HasOne("project1.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
